# netlify.toml

# Specify the build plugin
[[plugins]]
package = "netlify-plugin-flutter"

# Configure the plugin to use the channel you need (stable is default)
[plugins.inputs]
channel = "stable" # Or 'beta', 'master'
